# Generated by Django 2.0.3 on 2018-04-03 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(verbose_name='date uploaded')),
                ('user', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=200)),
                ('waveform_short', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_posted', models.DateTimeField(verbose_name='date posted')),
                ('user', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('audiofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bashMyWave.AudioFile')),
            ],
        ),
    ]
