# Generated by Django 2.0.3 on 2018-04-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bashMyWave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='audio_time',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
