# Generated by Django 2.0.3 on 2018-04-15 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bashMyWave', '0002_comment_audio_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='file_path',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='audio'),
            preserve_default=False,
        ),
    ]
